name: workfire
description: A beautiful, performant, and customizable firework widget for Flutter applications with realistic physics and animations.
version: 1.0.0
homepage: https://github.com/vlvcDev/workfire
repository: https://github.com/vlvcDev/workfire
issue_tracker: https://github.com/vlvcDev/workfire/issues
documentation: https://github.com/vlvcDev/workfire#readme
topics:
  - widget
  - animation
  - fireworks
  - effects
  - particles

environment:
  sdk: ^3.8.1
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  # This package is a Dart package that contains Flutter widgets
  # To learn more about Flutter packages: https://flutter.dev/developing-packages/

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
