name: workfire
description: A beautiful, performant, and customizable firework widget for Flutter applications with realistic physics and comprehensive animation controls.
version: 1.0.2
homepage: https://vlvcdev.github.io/workfire/
repository: https://github.com/vlvcDev/workfire
issue_tracker: https://github.com/vlvcDev/workfire/issues
documentation: https://github.com/vlvcDev/workfire#readme
topics:
  - widget
  - animation
  - fireworks
  - effects
  - ui

environment:
  sdk: ^3.8.1
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  # This package is a Dart package that contains Flutter widgets
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
